//Esta es una prueba de como hacer un regitro mediante Js aplicando cosas vistas en clase//

let nombre = prompt ("Ingrese su nombre:");
let edad = prompt ("Ingrese su edad:");

    if (edad >= 18) {
        console.log("Bienvenido + nombre, puedes ingresar");
    } 
    else {
        console.log("Lo siento + nombre, no puedes ingresar");
    }



    //Todavia no tengo claro que deseo hacer como proyecto final//